apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: http-echo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AntScare/cd-bootcamp.git"
    targetRevision: main
    path: "helm/http-echo-chart/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
